# Generated by Django 4.2.4 on 2023-08-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BenignDevApp', '0005_contact_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='IctResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, upload_to='doc')),
            ],
        ),
    ]
